name: test cypress e2e

# événément sur lequel lancer le workflow
on:
  push:
    branches: ["main", "test", "feature"]
  pull_request:
    branches: ["main", "test", "feature"]
  workflow_dispatch:

# décrire le workflow
jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    # décrire les étapes
    steps:
      # récupérer le code du projet
      - name: Checkout projet
        uses: actions/checkout@v5
      # installer php (composer + extension) https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      # avec extension mbstring, pdo_mysql, intl, sodium, zip version 8.4
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, intl, sodium, zip
          tools: composer
          coverage: none
      # créer la BDD (ligne de commande)
      - name: Create Test Database
      # avec la commande (mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS app_test;")
        run: |
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS app_test;"
      # créer les fichiers .env / env.test
      - name: Create .env files
        run: |
          echo "DATABASE_URL=\"mysql://root:root@127.0.0.1:3306/app_test?serverVersion=8.0&charset=utf8mb4\"" > .env.test
          echo "CORS_ALLOW_ORIGIN=\"^https?://(localhost|127\.0.0.1)(:[0-9]+)?$\"" >> .env.test
          cp .env.test .env
      # installer les dépendances (composer install)
      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist
      # migrer la structure de données (php/bin console d:m:m)
      - name: Database Migrations
        run: |
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
      # ÉTAPE CLÉ : Charger les données pour Cypress
      - name: Load Data Fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --env=test
      # démarrer le serveur PHP (php -S 127.0.0.1:8000 -t public &) run(saisir des commandes bash)
      - name: Start PHP Server
        run: |
          php -S 127.0.0.1:8000 -t public &
      # installer avec cypress - name: Cypress run
      - name: Cypress run
      # uses: cypress-io/github-action@v7
        uses: cypress-io/github-action@v7
        with:
          wait-on: 'http://127.0.0.1:8000'

deploy:
    runs-on: ubuntu-latest
    needs: e2e # Attend la réussite des tests
    if: github.ref == 'refs/heads/main' # Ne déploie que si on est sur la branche main
    steps:
      - name: Checkout projet
        uses: actions/checkout@v4

      # Setup PHP, Composer, extensions
      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql, sodium, zip
          tools: composer
          coverage: none
      
      # installation des dépendances composer prod
      - name: Installer dépendances Composer
        run: composer install --no-interaction --prefer-dist
      
      # build env.php for prod
      - name: Build .env for Production
        run: |
          echo "APP_ENV=prod" > .env
          echo "DATABASE_URL=\"mysql://${{ secrets.BDD_LOGIN }}:${{ secrets.BDD_PASSWORD }}@${{ secrets.FTP_SERVER }}:3306/${{ secrets.BDD_NAME }}?serverVersion=8.0&charset=utf8mb4\"" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET || '67d3f2932353522d252233b83d78d05b' }}" >> .env


      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./www/ # Dossier de destination sur ton hébergement
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**